### ISSUE TITLE
How to use it with Jackett?

### ISSUE THREAD

**Issue by hisakiyo** [Guisch/yggfetch#3]
Hi,
In the YGG indexer configuration I changed the "search and download URL" with my server's url running YGGFetch (something like XXX.XXXX.xyz) . Jackett tells me the host is unreachable but my url works in my browser.
Wouldn't the problem be the Jackett configuration?
Thanks for your work

**Comment by Zoz92** [comment]
Same as @hisakiyo 

![image](https://user-images.githubusercontent.com/66385795/83972901-1fa26380-a8e3-11ea-957b-70c90a19a1d3.png)

![image](https://user-images.githubusercontent.com/66385795/83972912-3648ba80-a8e3-11ea-9569-8e55206b814d.png)

**Comment by gdlx** [comment]
Jackett doesn't accept the port number. As I'm using a Traefik reverse proxy, I've just put yggfetch behind it (using a specific hostname instead of a port number) and Jackett can connect, but there are other issues for now...
![image](https://user-images.githubusercontent.com/1533042/83978060-22ae4b80-a905-11ea-98c1-6eb1552baca2.png)

But yeah, Jackett should accept port numbers to ease basic setups.

**Comment by Guisch** [comment]
Hey, YGG removed the cloudflare protection. This project is now useless I'm archiving it.
